// Code generated by ogen, DO NOT EDIT.
package api

type CreateDownloadRes interface {
	createDownloadRes()
}

type GetChannelInfoRes interface {
	getChannelInfoRes()
}

type GetDownloadRes interface {
	getDownloadRes()
}

type ListDownloadsRes interface {
	listDownloadsRes()
}
