// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateDownload implements createDownload operation.
	//
	// ダウンロードを開始.
	//
	// POST /api/{secret}/downloads
	CreateDownload(ctx context.Context, req *CreateDownloadRequest, params CreateDownloadParams) (*Download, error)
	// GetChannelInfo implements getChannelInfo operation.
	//
	// チャンネル情報を取得.
	//
	// GET /api/{secret}
	GetChannelInfo(ctx context.Context, params GetChannelInfoParams) (*ChannelInfoResponse, error)
	// GetDownload implements getDownload operation.
	//
	// ダウンロード情報を取得.
	//
	// GET /api/{secret}/downloads/{id}
	GetDownload(ctx context.Context, params GetDownloadParams) (*Download, error)
	// ListDownloads implements listDownloads operation.
	//
	// ダウンロード一覧を取得.
	//
	// GET /api/{secret}/downloads
	ListDownloads(ctx context.Context, params ListDownloadsParams) (*DownloadListResponse, error)
	// NewError creates *ErrorResponseStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorResponseStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
