// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateDownload implements createDownload operation.
	//
	// ダウンロードを開始.
	//
	// POST /api/{secret}/downloads
	CreateDownload(ctx context.Context, req *CreateDownloadRequest, params CreateDownloadParams) (CreateDownloadRes, error)
	// GetChannelInfo implements getChannelInfo operation.
	//
	// チャンネル情報を取得.
	//
	// GET /api/{secret}
	GetChannelInfo(ctx context.Context, params GetChannelInfoParams) (GetChannelInfoRes, error)
	// GetDownload implements getDownload operation.
	//
	// ダウンロード情報を取得.
	//
	// GET /api/{secret}/downloads/{id}
	GetDownload(ctx context.Context, params GetDownloadParams) (GetDownloadRes, error)
	// Healthcheck implements healthcheck operation.
	//
	// サービスの死活確認.
	//
	// GET /health
	Healthcheck(ctx context.Context) (*HealthResponse, error)
	// ListDownloads implements listDownloads operation.
	//
	// ダウンロード一覧を取得.
	//
	// GET /api/{secret}/downloads
	ListDownloads(ctx context.Context, params ListDownloadsParams) (ListDownloadsRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
