// Code generated by ogen, DO NOT EDIT.

package api

import (
	"fmt"
	"time"

	"github.com/go-faster/errors"
)

func (s *ErrorResponseStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// チャンネル情報レスポンス.
// Ref: #/components/schemas/ChannelInfoResponse
type ChannelInfoResponse struct {
	Name string `json:"name"`
}

// GetName returns the value of Name.
func (s *ChannelInfoResponse) GetName() string {
	return s.Name
}

// SetName sets the value of Name.
func (s *ChannelInfoResponse) SetName(val string) {
	s.Name = val
}

// ダウンロード開始リクエスト.
// Ref: #/components/schemas/CreateDownloadRequest
type CreateDownloadRequest struct {
	URL string `json:"url"`
}

// GetURL returns the value of URL.
func (s *CreateDownloadRequest) GetURL() string {
	return s.URL
}

// SetURL sets the value of URL.
func (s *CreateDownloadRequest) SetURL(val string) {
	s.URL = val
}

// ダウンロード情報.
// Ref: #/components/schemas/Download
type Download struct {
	ID          string         `json:"id"`
	URL         string         `json:"url"`
	Title       OptString      `json:"title"`
	Status      DownloadStatus `json:"status"`
	Progress    int32          `json:"progress"`
	Filename    OptString      `json:"filename"`
	Error       OptString      `json:"error"`
	CreatedAt   time.Time      `json:"createdAt"`
	CompletedAt OptDateTime    `json:"completedAt"`
}

// GetID returns the value of ID.
func (s *Download) GetID() string {
	return s.ID
}

// GetURL returns the value of URL.
func (s *Download) GetURL() string {
	return s.URL
}

// GetTitle returns the value of Title.
func (s *Download) GetTitle() OptString {
	return s.Title
}

// GetStatus returns the value of Status.
func (s *Download) GetStatus() DownloadStatus {
	return s.Status
}

// GetProgress returns the value of Progress.
func (s *Download) GetProgress() int32 {
	return s.Progress
}

// GetFilename returns the value of Filename.
func (s *Download) GetFilename() OptString {
	return s.Filename
}

// GetError returns the value of Error.
func (s *Download) GetError() OptString {
	return s.Error
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Download) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetCompletedAt returns the value of CompletedAt.
func (s *Download) GetCompletedAt() OptDateTime {
	return s.CompletedAt
}

// SetID sets the value of ID.
func (s *Download) SetID(val string) {
	s.ID = val
}

// SetURL sets the value of URL.
func (s *Download) SetURL(val string) {
	s.URL = val
}

// SetTitle sets the value of Title.
func (s *Download) SetTitle(val OptString) {
	s.Title = val
}

// SetStatus sets the value of Status.
func (s *Download) SetStatus(val DownloadStatus) {
	s.Status = val
}

// SetProgress sets the value of Progress.
func (s *Download) SetProgress(val int32) {
	s.Progress = val
}

// SetFilename sets the value of Filename.
func (s *Download) SetFilename(val OptString) {
	s.Filename = val
}

// SetError sets the value of Error.
func (s *Download) SetError(val OptString) {
	s.Error = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Download) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetCompletedAt sets the value of CompletedAt.
func (s *Download) SetCompletedAt(val OptDateTime) {
	s.CompletedAt = val
}

// ダウンロード一覧レスポンス.
// Ref: #/components/schemas/DownloadListResponse
type DownloadListResponse struct {
	Downloads []Download `json:"downloads"`
}

// GetDownloads returns the value of Downloads.
func (s *DownloadListResponse) GetDownloads() []Download {
	return s.Downloads
}

// SetDownloads sets the value of Downloads.
func (s *DownloadListResponse) SetDownloads(val []Download) {
	s.Downloads = val
}

// ダウンロードステータス.
// Ref: #/components/schemas/DownloadStatus
type DownloadStatus string

const (
	DownloadStatusPending     DownloadStatus = "pending"
	DownloadStatusDownloading DownloadStatus = "downloading"
	DownloadStatusConverting  DownloadStatus = "converting"
	DownloadStatusCompleted   DownloadStatus = "completed"
	DownloadStatusError       DownloadStatus = "error"
)

// AllValues returns all DownloadStatus values.
func (DownloadStatus) AllValues() []DownloadStatus {
	return []DownloadStatus{
		DownloadStatusPending,
		DownloadStatusDownloading,
		DownloadStatusConverting,
		DownloadStatusCompleted,
		DownloadStatusError,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s DownloadStatus) MarshalText() ([]byte, error) {
	switch s {
	case DownloadStatusPending:
		return []byte(s), nil
	case DownloadStatusDownloading:
		return []byte(s), nil
	case DownloadStatusConverting:
		return []byte(s), nil
	case DownloadStatusCompleted:
		return []byte(s), nil
	case DownloadStatusError:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *DownloadStatus) UnmarshalText(data []byte) error {
	switch DownloadStatus(data) {
	case DownloadStatusPending:
		*s = DownloadStatusPending
		return nil
	case DownloadStatusDownloading:
		*s = DownloadStatusDownloading
		return nil
	case DownloadStatusConverting:
		*s = DownloadStatusConverting
		return nil
	case DownloadStatusCompleted:
		*s = DownloadStatusCompleted
		return nil
	case DownloadStatusError:
		*s = DownloadStatusError
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// エラーレスポンス.
// Ref: #/components/schemas/ErrorResponse
type ErrorResponse struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *ErrorResponse) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *ErrorResponse) SetMessage(val string) {
	s.Message = val
}

// ErrorResponseStatusCode wraps ErrorResponse with StatusCode.
type ErrorResponseStatusCode struct {
	StatusCode int
	Response   ErrorResponse
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorResponseStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorResponseStatusCode) GetResponse() ErrorResponse {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorResponseStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorResponseStatusCode) SetResponse(val ErrorResponse) {
	s.Response = val
}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}
