// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateDownload implements createDownload operation.
//
// ダウンロードを開始.
//
// POST /api/{secret}/downloads
func (UnimplementedHandler) CreateDownload(ctx context.Context, req *CreateDownloadRequest, params CreateDownloadParams) (r CreateDownloadRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetChannelInfo implements getChannelInfo operation.
//
// チャンネル情報を取得.
//
// GET /api/{secret}
func (UnimplementedHandler) GetChannelInfo(ctx context.Context, params GetChannelInfoParams) (r GetChannelInfoRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDownload implements getDownload operation.
//
// ダウンロード情報を取得.
//
// GET /api/{secret}/downloads/{id}
func (UnimplementedHandler) GetDownload(ctx context.Context, params GetDownloadParams) (r GetDownloadRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Healthcheck implements healthcheck operation.
//
// サービスの死活確認.
//
// GET /health
func (UnimplementedHandler) Healthcheck(ctx context.Context) (r *HealthResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ListDownloads implements listDownloads operation.
//
// ダウンロード一覧を取得.
//
// GET /api/{secret}/downloads
func (UnimplementedHandler) ListDownloads(ctx context.Context, params ListDownloadsParams) (r ListDownloadsRes, _ error) {
	return r, ht.ErrNotImplemented
}
