// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// CreateDownloadParams is parameters of createDownload operation.
type CreateDownloadParams struct {
	Secret string
}

func unpackCreateDownloadParams(packed middleware.Parameters) (params CreateDownloadParams) {
	{
		key := middleware.ParameterKey{
			Name: "secret",
			In:   "path",
		}
		params.Secret = packed[key].(string)
	}
	return params
}

func decodeCreateDownloadParams(args [1]string, argsEscaped bool, r *http.Request) (params CreateDownloadParams, _ error) {
	// Decode path: secret.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "secret",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Secret = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "secret",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetChannelInfoParams is parameters of getChannelInfo operation.
type GetChannelInfoParams struct {
	Secret string
}

func unpackGetChannelInfoParams(packed middleware.Parameters) (params GetChannelInfoParams) {
	{
		key := middleware.ParameterKey{
			Name: "secret",
			In:   "path",
		}
		params.Secret = packed[key].(string)
	}
	return params
}

func decodeGetChannelInfoParams(args [1]string, argsEscaped bool, r *http.Request) (params GetChannelInfoParams, _ error) {
	// Decode path: secret.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "secret",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Secret = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "secret",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetDownloadParams is parameters of getDownload operation.
type GetDownloadParams struct {
	Secret string
	ID     string
}

func unpackGetDownloadParams(packed middleware.Parameters) (params GetDownloadParams) {
	{
		key := middleware.ParameterKey{
			Name: "secret",
			In:   "path",
		}
		params.Secret = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(string)
	}
	return params
}

func decodeGetDownloadParams(args [2]string, argsEscaped bool, r *http.Request) (params GetDownloadParams, _ error) {
	// Decode path: secret.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "secret",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Secret = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "secret",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: id.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// ListDownloadsParams is parameters of listDownloads operation.
type ListDownloadsParams struct {
	Secret string
}

func unpackListDownloadsParams(packed middleware.Parameters) (params ListDownloadsParams) {
	{
		key := middleware.ParameterKey{
			Name: "secret",
			In:   "path",
		}
		params.Secret = packed[key].(string)
	}
	return params
}

func decodeListDownloadsParams(args [1]string, argsEscaped bool, r *http.Request) (params ListDownloadsParams, _ error) {
	// Decode path: secret.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "secret",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Secret = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "secret",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
