// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateDownloadOperation OperationName = "CreateDownload"
	GetChannelInfoOperation OperationName = "GetChannelInfo"
	ListDownloadsOperation  OperationName = "ListDownloads"
)
