/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/{secret}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description チャンネル情報を取得 */
        get: operations["getChannelInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{secret}/downloads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ダウンロード一覧を取得 */
        get: operations["listDownloads"];
        put?: never;
        /** @description ダウンロードを開始 */
        post: operations["createDownload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{secret}/downloads/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ダウンロード情報を取得 */
        get: operations["getDownload"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description チャンネル情報レスポンス */
        ChannelInfoResponse: {
            name: string;
        };
        /** @description ダウンロード開始リクエスト */
        CreateDownloadRequest: {
            url: string;
        };
        /** @description ダウンロード情報 */
        Download: {
            id: string;
            url: string;
            title?: string;
            status: components["schemas"]["DownloadStatus"];
            /** Format: int32 */
            progress: number;
            filename?: string;
            error?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            completedAt?: string;
        };
        /** @description ダウンロード一覧レスポンス */
        DownloadListResponse: {
            downloads: components["schemas"]["Download"][];
        };
        /**
         * @description ダウンロードステータス
         * @enum {string}
         */
        DownloadStatus: "pending" | "downloading" | "converting" | "completed" | "error";
        /** @description エラーレスポンス */
        ErrorResponse: {
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getChannelInfo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                secret: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelInfoResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listDownloads: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                secret: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadListResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createDownload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                secret: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDownloadRequest"];
            };
        };
        responses: {
            /** @description The request has been accepted for processing, but processing has not yet completed. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Download"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getDownload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                secret: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Download"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
