// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const createDownload = `-- name: CreateDownload :one
INSERT INTO downloads (id, channel, url, status, progress)
VALUES (?1, ?2, ?3, 'pending', 0)
RETURNING id, channel, url, title, status, progress, filename, error, created_at, completed_at
`

type CreateDownloadParams struct {
	ID      string
	Channel string
	Url     string
}

func (q *Queries) CreateDownload(ctx context.Context, arg CreateDownloadParams) (Download, error) {
	row := q.db.QueryRowContext(ctx, createDownload, arg.ID, arg.Channel, arg.Url)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.Channel,
		&i.Url,
		&i.Title,
		&i.Status,
		&i.Progress,
		&i.Filename,
		&i.Error,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getDownloadsByChannel = `-- name: GetDownloadsByChannel :many
SELECT id, channel, url, title, status, progress, filename, error, created_at, completed_at FROM downloads
WHERE channel = ?1
ORDER BY created_at DESC
`

func (q *Queries) GetDownloadsByChannel(ctx context.Context, channel string) ([]Download, error) {
	rows, err := q.db.QueryContext(ctx, getDownloadsByChannel, channel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Download
	for rows.Next() {
		var i Download
		if err := rows.Scan(
			&i.ID,
			&i.Channel,
			&i.Url,
			&i.Title,
			&i.Status,
			&i.Progress,
			&i.Filename,
			&i.Error,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDownloadStatus = `-- name: UpdateDownloadStatus :exec
UPDATE downloads
SET status       = ?1,
    progress     = ?2,
    title        = ?3,
    filename     = ?4,
    error        = ?5,
    completed_at = CASE WHEN :status IN ('completed', 'error') THEN CURRENT_TIMESTAMP ELSE NULL END
WHERE id = ?6
`

type UpdateDownloadStatusParams struct {
	Status   string
	Progress int64
	Title    sql.NullString
	Filename sql.NullString
	Error    sql.NullString
	ID       string
}

func (q *Queries) UpdateDownloadStatus(ctx context.Context, arg UpdateDownloadStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateDownloadStatus,
		arg.Status,
		arg.Progress,
		arg.Title,
		arg.Filename,
		arg.Error,
		arg.ID,
	)
	return err
}
