// Package handler implements the ogen-generated Handler interface.
// IMPORTANT: Run `mise run gen` before building to generate the api package.
package handler

import (
	"context"
	"database/sql"
	"net/url"
	"time"

	"media-downloader/api"
	"media-downloader/db"
	"media-downloader/service"
)

// Handler implements api.Handler (generated by ogen).
type Handler struct {
	svc *service.Service
}

func New(svc *service.Service) *Handler {
	return &Handler{svc: svc}
}

// GetChannelInfo handles GET /api/{secret}
func (h *Handler) GetChannelInfo(_ context.Context, params api.GetChannelInfoParams) (api.GetChannelInfoRes, error) {
	ch, ok := h.svc.GetChannel(params.Secret)
	if !ok {
		return &api.ErrorResponseStatusCode{
			StatusCode: 404,
			Response:   api.ErrorResponse{Message: "channel not found"},
		}, nil
	}
	return &api.ChannelInfoResponse{Name: ch.Name}, nil
}

// ListDownloads handles GET /api/{secret}/downloads
func (h *Handler) ListDownloads(ctx context.Context, params api.ListDownloadsParams) (api.ListDownloadsRes, error) {
	if _, ok := h.svc.GetChannel(params.Secret); !ok {
		return &api.ErrorResponseStatusCode{
			StatusCode: 404,
			Response:   api.ErrorResponse{Message: "channel not found"},
		}, nil
	}

	downloads, err := h.svc.ListDownloads(ctx, params.Secret)
	if err != nil {
		return &api.ErrorResponseStatusCode{
			StatusCode: 500,
			Response:   api.ErrorResponse{Message: err.Error()},
		}, nil
	}

	items := make([]api.Download, len(downloads))
	for i, d := range downloads {
		items[i] = toAPIDownload(d)
	}
	return &api.DownloadListResponse{Downloads: items}, nil
}

// CreateDownload handles POST /api/{secret}/downloads
func (h *Handler) CreateDownload(ctx context.Context, req *api.CreateDownloadRequest, params api.CreateDownloadParams) (api.CreateDownloadRes, error) {
	if _, ok := h.svc.GetChannel(params.Secret); !ok {
		return &api.ErrorResponseStatusCode{
			StatusCode: 404,
			Response:   api.ErrorResponse{Message: "channel not found"},
		}, nil
	}
	if !isValidYouTubeURL(req.URL) {
		return &api.ErrorResponseStatusCode{
			StatusCode: 400,
			Response:   api.ErrorResponse{Message: "invalid YouTube URL"},
		}, nil
	}

	download, err := h.svc.CreateDownload(ctx, params.Secret, req.URL)
	if err != nil {
		return &api.ErrorResponseStatusCode{
			StatusCode: 500,
			Response:   api.ErrorResponse{Message: err.Error()},
		}, nil
	}

	result := toAPIDownload(download)
	return &result, nil
}

// isValidYouTubeURL validates that the URL is a YouTube URL.
func isValidYouTubeURL(rawURL string) bool {
	u, err := url.Parse(rawURL)
	if err != nil {
		return false
	}
	switch u.Host {
	case "www.youtube.com", "youtube.com", "youtu.be", "m.youtube.com":
		return true
	}
	return false
}

// toAPIDownload converts a db.Download to an api.Download.
func toAPIDownload(d db.Download) api.Download {
	out := api.Download{
		ID:        d.ID,
		URL:       d.Url,
		Status:    api.DownloadStatus(d.Status),
		Progress:  int32(d.Progress),
		CreatedAt: d.CreatedAt,
	}
	if d.Title.Valid {
		out.Title = api.NewOptString(d.Title.String)
	}
	if d.Filename.Valid {
		out.Filename = api.NewOptString(d.Filename.String)
	}
	if d.Error.Valid {
		out.Error = api.NewOptString(d.Error.String)
	}
	if d.CompletedAt.Valid {
		out.CompletedAt = api.NewOptDateTime(d.CompletedAt.Time.UTC().Truncate(time.Second))
	}
	return out
}

// Ensure db.NullTime is handled — helper used in toAPIDownload.
var _ = sql.NullTime{}
