services:
  media-downloader:
    image: ghcr.io/irumaru/media-downloader/mono:latest
    ports:
      - "8080:8080"
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./data:/app/data
      #- /mnt/nas1/music_a:/app/data/music_a
    restart: unless-stopped
