name: test-e2e

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup mise
        uses: jdx/mise-action@v4
        with:
          install: true
          cache: true

      - name: Docker Compose Up
        run: docker compose up
      
      - name: Run E2E Tests
        run: mise run test:e2e
